FROM node:slim

# MÉTADONNÉES DE L'IMAGE
LABEL version="1.0" maintainer="D <d@gmail.com>"

# VARIABLES TEMPORAIRES
ARG APT_FLAGS="-q -y"
ARG DOCUMENTROOT="/usr/src/app"

# RÉPERTOIRE DE TRAVAIL
WORKDIR  ${DOCUMENTROOT}

COPY package.json .

# Couche node
RUN npm i

COPY db/articles.sql / 

# pour le volume
RUN mkdir /data

# OUVERTURE DU PORT HTTP
EXPOSE 3000

# DÉMARRAGE DES SERVICES LORS DE L'EXÉCUTION DE L'IMAGE
CMD [ "npm", "start" ]

# copie des autres fichiers
COPY . .