FROM node:slim

# MÉTADONNÉES DE L'IMAGE
LABEL version="1.0" maintainer="D <d@gmail.com>"

# VARIABLES TEMPORAIRES
ARG APT_FLAGS="-q -y"
ARG DOCUMENTROOT="/usr/src/app"

# RÉPERTOIRE DE TRAVAIL
WORKDIR  ${DOCUMENTROOT}

COPY package.json .

# installation des dépendances
RUN npm i

# création d'un volume pour la bd
#RUN mkdir /data

# OUVERTURE DU PORT HTTP
EXPOSE 3000

# DÉMARRAGE DES SERVICES LORS DE L'EXÉCUTION DE L'IMAGE
CMD [ "npm", "start" ]

# copie des autres fichiers
COPY index.js .